version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD=bookmyshow
      - POSTGRES_DB=bookmyshowdb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local
